sudo: required
language: bash
dist: focal

addons:
    apt:
        packages:
            - linux-image-generic
            - libguestfs-tools

jobs:
    include:
        - stage: travis-ci-vs-libguestfs
          arch: s390x
          language: bash
          script: ./go
