sudo: required
language: bash
dist: bionic

addons:
    apt:
        packages:
            - linux-image-generic
            - libguestfs-tools

jobs:
    include:
        - stage: travis-ci-vs-libguestfs 
          name: x86_64
          language: bash
          script: ./go

        - name: s390x
          arch: s390x
          language: bash
          script: ./go
